export const TRANSACTIONS = "TRANSACTIONS";
export const NEW_TRANSACTIONS = "NEW_TRANSACTIONS";
export const REMOVE_TRANSACTIONS = "REMOVE_TRANSACTIONS";
export const EDIT_TRANSACTIONS = "EDIT_TRANSACTIONS";

export const CATEGORY_ITEMS = "CATEGORY_ITEMS";
export const ADD_CATEGORY_ITEM = "ADD_CATEGORY_ITEM";
export const EDIT_CATEGORY_ITEM = "EDIT_CATEGORY_ITEM";
export const REMOVE_CATEGORY_ITEM = "REMOVE_CATEGORY_ITEM";